#!/usr/bin/env bash

## Virsh devices
gpu="0000:02:00.0"
aud="0000:02:00.1"

devices=("$gpu" "$aud")

function bind_vfio {
    modprobe vfio-pci

    for dev in "${devices[@]}"; do
        echo "vfio-pci" > "/sys/bus/pci/devices/$dev/driver_override"

        if [ -L "/sys/bus/pci/devices/$dev/driver" ]; then
            echo "$dev" > "/sys/bus/pci/devices/$dev/driver/unbind"
        fi

        echo "$dev" > "/sys/bus/pci/drivers/vfio-pci/bind"
    done
}

function unbind_vfio {
    for dev in "${devices[@]}"; do
        echo "" > "/sys/bus/pci/devices/$dev/driver_override"

        if [ -L "/sys/bus/pci/devices/$dev/driver" ]; then
            echo "$dev" > "/sys/bus/pci/devices/$dev/driver/unbind"
        fi

        echo 1 > "/sys/bus/pci/devices/$dev/remove"
    done

    echo 1 > "/sys/bus/pci/rescan"
}
